### ISSUE TITLE
Revdep failures, released dplyr, devel sf

### ISSUE THREAD

**Issue by rsbivand** [david6marsh/himach#25]
Re: #22
[testthat.Rout.zip](https://github.com/david6marsh/himach/files/10091114/testthat.Rout.zip)
[00check.log](https://github.com/david6marsh/himach/files/10091117/00check.log)

these are I think new testthat failures.

**Comment by david6marsh** [comment]
Yes, thanks. Looks like I need to do some updating to the latest package versions.

Working on it.

**Comment by rsbivand** [comment]
These remain with your development version:
[testthat.Rout.zip](https://github.com/david6marsh/himach/files/10139954/testthat.Rout.zip)
[00check.log](https://github.com/david6marsh/himach/files/10139956/00check.log)

**Comment by david6marsh** [comment]
OK. But odd, since I'm not getting these on my machine, nor when [GitHub checks on other machines](https://github.com/david6marsh/himach/actions/runs/3600267070). 

I'll see how I can reproduce the errors and investigate.

**Comment by rsbivand** [comment]
```
> sf::sf_extSoftVersion()
          GEOS           GDAL         proj.4 GDAL_with_GEOS     USE_PROJ_H 
      "3.11.1"        "3.6.0"        "9.1.1"         "true"         "true" 
          PROJ 
       "9.1.1" 
```
May not be the cause. CI is only effective when it is forward-looking (effectively never).

**Comment by rsbivand** [comment]
It is possible that **testthat** is imposing its `edition_deprecate(3, "expect_known_value()", "Please use `expect_snapshot_value()` instead")` deprecation, I'm using `3.1.5`. Running outside **testthat**:
```
> all.equal(readRDS("himach.Rcheck/tests/testthat/known/default_airport_EGLL"), z)
[1] TRUE # line 33
> all.equal(readRDS("himach.Rcheck/tests/testthat/known/TEST_airport"), airports)
[1] TRUE # line 42
```

**Comment by david6marsh** [comment]
Upgraded to edition 3 of testthat. Current dev version checks ok on CRAN now. (except for dev-level version number)
